trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  MajorVersion: 1
  MinorVersion: 0
  PatchVersion: 0

stages:
- stage: Master_Name
  displayName: Master Version Name
  condition: eq(variables['Build.SourceBranchName'], 'master')
  jobs:
  - job: Set_Master_Version_Number
    variables:
       brpatch: $(version)
    steps:
      - bash: |
           echo "##vso[build.updatebuildnumber]$(MajorVersion).$(MinorVersion).$(PatchVersion).$(brpatch)"
        name: SetBranchBuildName
  
- stage: Branch_Name
  displayName: Branch Version Name
  condition: ne(variables['Build.SourceBranchName'], 'master')
  jobs:
  - job: Set_Branch_Version_Name
    steps:
      - bash: |
           echo "##vso[build.updatebuildnumber]$(Build.SourceBranchName)"
        name: SetBranchBuildName
        
- stage:
  displayName: Build Steps
  condition: or(not(failed('Master_Name')), not(failed('Branch_Name')))
  jobs:
    - job: Build_Steps
      steps:

      - task: DownloadBuildArtifacts@0
        displayName: Download icGeneric.dll
        inputs:
          buildType: 'specific'
          project: 'iclr-build'
          pipeline: 'icGeneric'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          downloadType: 'specific'
          downloadPath: './'

      - task: PowerShell@2
        displayName: Unzip/copy icGeneric
        inputs:
          targetType: 'inline'
          script: |
            cd icGeneric
            Expand-Archive *.zip .\            
            rm *.zip
            cp icGeneric* ../

      - task: DownloadBuildArtifacts@0
        displayName: Download icLogger artifact
        inputs:
          buildType: 'specific'
          project: 'iclr-build'
          pipeline: 'icLogger'
          specificBuildWithTriggering: true
          buildVersionToDownload: 'latest'
          downloadType: 'specific'
          downloadPath: './'

      - task: PowerShell@2
        displayName: Unzip/copy icLogger + dependencies
        inputs:
          targetType: 'inline'
          script: |
            cd icLogger
            Expand-Archive *.zip .\            
            rm *.zip
            cp icLogger* ../

      - task: NuGetCommand@2
        inputs:
          command: 'restore'
          restoreSolution: 'OCCprocess.sln'
          feedsToUse: 'select'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: false
          projects: './OCCprocess.csproj'
          arguments: '-c Release --self-contained true -r win-x86'
          zipAfterPublish: false

      - task: PowerShell@2
        displayName: Archive Files
        inputs:
          targetType: 'inline'
          script: |
            Get-ChildItem -Recurse
            Compress-Archive -Path "$(Build.SourcesDirectory)/bin/Release/netcoreapp3.1/win-x86/publish/*" -DestinationPath "$(Build.ArtifactStagingDirectory)/OCCprocess_$(Build.BuildId).zip"
            
      - task: PublishBuildArtifacts@1
        displayName: Publish OCCprocess artifact
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: OCCprocess

        # Create Release
      - task: GitHubRelease@1
        displayName: 'Create GitHub Release'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
            gitHubConnection: 'ICLR-Github'
            repositoryName: 'inteliclear/OCCprocess'
            action: 'create'
            target: '$(Build.SourceVersion)'
            tagSource: 'userSpecifiedTag'
            tag: $(Build.BuildNumber)
            changeLogCompareToRelease: 'lastFullRelease'
            changeLogType: 'commitBased'          
